version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wehood
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wehood-network

volumes:
  postgres_data:
  media_uploads:

networks:
  wehood-network:
    driver: bridge 