version: '3.8'

services:
  app:
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=wehood_db
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - wehood-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wehood_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wehood-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
    environment:
      MH_HOSTNAME: mailhog

volumes:
  postgres_data:

networks:
  wehood-network:
    driver: bridge 